### ISSUE TITLE
403 Errors when creating an automation

### ISSUE THREAD

**Issue by R-NK** [PrefectHQ/terraform-provider-prefect#324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave _+1_ or _me too_ comments, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform Version
1.5.7

### Affected Resource(s)

* prefect_automation

#### resource
```tf
resource "prefect_automation" "test" {
  name = "test"
  trigger = {
    event = {
      match = jsonencode({
        "prefect.resource.id" : "prefect.deployment.*"
      })
      expect    = ["prefect.deployment.ready"]
      for_each  = ["prefect.resource.id"]
      posture   = "Reactive"
      threshold = 1
      within    = 0
    }
  }
}
```
#### provider
```tf
provider "prefect" {
  account_id   = "xxxx"
  workspace_id = "xxxx"
  api_key      = var.prefect_api_key_prod
}
```
### Debug Output

```sh
│ Error: Error during create Automation
│ 
│   with prefect_automation.test,
│   on automation.tf line 29, in resource "prefect_automation" "test":
│   29: resource "prefect_automation" "test" {
│ 
│ Could not create Automation, unexpected error: failed to create automation: status code=403 Forbidden, error={"detail":"Workspace scopes missing: manage_automations"}
```
https://gist.github.com/R-NK/43692e209e71414108423543b668e487
### Expected Behavior
An automation is created.

### Actual Behavior
A 403 error occurs, and the automation is not created.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by parkedwards** [comment]
hey @R-NK -- the error message in the 403 should tell you what is missing.  it seems that whatever API Key you're using for your Terraform controller (eg. the key you pass into the provider config or the `PREFECT_API_KEY` environment variable) doesn't have the right permissions to create automations

please see this section in the [Getting Started documentation](https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/guides/getting-started#rbac--permissions) for more information.  Since this isn't related to an issue in the provider itself, I'm going to close this - but please feel free to open a new issue if needed
