### ISSUE TITLE
Service Account Rotation

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/terraform-provider-prefect#325]
Can I get some clarity around API key rotation for service accounts. Is the rotate API only being called when the value of old_key_expires_in_seconds changes, not every time the plan is applied right?  So if I were to want to force a rotation I would change to 301, 299, etc?  

It would be great to have something like [keepers](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password#keepers-1) to make rotation less dependent on an actual functional aspect like the expiry time.

```
resource "prefect_service_account" "test1" {
  name = "test1"
  account_role_name = "Member"
  old_key_expires_in_seconds = 300
}
```

**Comment by jbnitorum** [comment]
@EmilRex

**Comment by parkedwards** [comment]
hey @jbnitorum,

there are actually two different `expiration` on this resource that might answer your q:

[`api_key_expiration`](https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/service_account#api_key_expiration-1) - this is the key attribute that controls key imperative key expiration.  You set this to define an expiry time for a new key OR rotate the current key.  Changing this attribute calls the `/rotate_api_key` endpoint.  Setting this to `null` will make this key never expire.

[`old_key_expires_in_seconds `](https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/service_account#old_key_expires_in_seconds-1) - this is an optional parameter and only takes effect if a rotate action is taken, eg. `api_key_expiration` is changed as described above.  Since rotating a key normally invalidates the current key and creates a new one, this is an optional parameter on our API that allows both keys to exist for the period defined in `old_key_expires_in_seconds` so that one can handle key rotations gracefully in their consumer.  you might not need this

as far as support for a `keepers` like interface - could you describe the use case you were envisioning? Most of the use cases we've encountered comes with SA keys being time bound, so our examples use the `time_rotating` [resource](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating#triggers-1) to handle this

**Comment by jbnitorum** [comment]
It would be something like this:

```
resource "prefect_service_account" "test1" {
  name = "test1"
  account_role_name = "Member"
  old_key_expires_in_seconds = 300
  keepers = {"secret_version": 1}
}
```

If you wanted to rotate the key while maintaining the old key for 300 seconds you would change to:

```
resource "prefect_service_account" "test1" {
  name = "test1"
  account_role_name = "Member"
  old_key_expires_in_seconds = 300
  keepers = {"secret_version": 2}
}
```

The keepers value is just an arbitrary map of values that when changed triggers rotation.  I have secret_version here, but it could be anything.

Separately, could you confirm above that if I changed the old_key_expires_in_seconds from 300 to 301 that that would trigger rotation?  Based on the explanation above it seems tricky to force rotate a key that you never want to expire.  If I have key that has no expiration and I want to replace it with a new key that I don't want to expire then I'm going from null to null on api_key_expiration... so that doesn't trigger a change.... unless I'm missing something.

**Comment by parkedwards** [comment]
> Based on the explanation above it seems tricky to force rotate a key that you never want to expire

Bingo, this is the use case that we're missing.  Looks like we have a gap in our implementation here for this that we'll want to address

> Separately, could you confirm above that if I changed the old_key_expires_in_seconds from 300 to 301 that that would trigger rotation

It would not; the provider currently kicks in the rotate call on change to the `api_key_expiration` attribute only.  but your use case is revealing that we'd need to be able to support rotating non-expiring keys w/o re-creating the SA itself. 

we'll get a fix in for this, but i can't provide an estimate.  if you're blocked and want to mimic your desired behavior, you could theoretically do something like this:

```hcl
provider "time" {}
resource "time_rotating" "very_far_into_future" {
  rotation_years = 10
  triggers = {} # your arbitrary map here, which acts as a `keepers` interface
}

resource "prefect_service_account" "example" {
  name               = "my-service-account"
  api_key_expiration = time_rotating.very_far_into_future.rotation_rfc3339
}

```

i'll leave this issue open so we can link it to the fix.  thanks again for raising this and describing your use case

**Comment by parkedwards** [comment]
hey @jbnitorum - [try giving 2.12.3 a go](https://registry.terraform.io/providers/PrefectHQ/prefect/2.12.3/docs/resources/service_account), with the new `api_key_keepers` map on the resource

**Comment by jbnitorum** [comment]
@parkedwards thanks for getting to this so fast!
